version: "2"
services:
    node:
        image: "node:app"
        working_dir: /home/node/app
        user: node
        #environment:
        #    - NODE_ENV=production
        #    
        privileged: true
        volumes:
            - ./:/home/node/app:rw
            - /home/node/app/node_modules
            - /var/run/docker.sock:/var/run/docker.sock
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
        ports:
            - 3000:3000
            - 3002:3002
            - 3443:3443
            - 3011:3011
        command: "npm run deploy"
        environment:
            - DISPLAY=:0
            - DOMAIN=localhost
            - DOCKER_IP=0.0.0.0 
            - DOCKER_IMAGE=hanson:paper
            - STREAM_IP=localhost
            - STREAM_PORT=5443
            - PROTOO_IP=0.0.0.0
            - PROTOO_PORT=3443
            - HTTP_IP=0.0.0.0
            - HTTPS_IP=0.0.0.0
            - HTTP_PORT=3011
            - HTTPS_PORT=7000
            - RTMP_IP=0.0.0.0
            - RTMP_PORT=5442
            - RESOLUTION_WIDTH=1366
            - RESOLUTION_HEIGHT=768
            - RPC_IP=0.0.0.0
            - RPC_PORT=3111
            - RTP_AUDIO_IP=0.0.0.0
            - RTP_AUDIO_PORT=5002
            - RTP_VIDEO_IP=0.0.0.0
            - RTP_VIDEO_PORT=5005
        links:
            - mongodb
            - nginx
        depends_on:
            - mongodb
            - nginx
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
              #volumes:
              #- ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet
    nginx:
        image: nginx:app
        container_name: "nginx_hoster"
        volumes:
            - ./:/home/node/app:rw
        ports: 
        - 5442:5442
        - 5443:5443
